### ISSUE TITLE
AMDX Extension: Configure sDelete

### ISSUE THREAD

**Issue by EUCweb** [EUCweb/BIS-F#12]
_From @matthias-schimm on March 12, 2018 20:30_

if using Citrix MCS, VMware Horizon View, Microsoft only sDelete can be run on the Systemdrive during sealing only.
 
IF Citrix PVS is used, if sDelete is enabled in the ADMX, it runs on the PVS WriteCacheDisk if the Disk is in shared Mode only every boot. 

sdelete can alos be run on:
MCS (c:drive)
AppLayering - outside ELM

_Copied from original issue: EUCweb/BIS-F#16_

**Comment by matthias-schlimm** [comment]
![BISF-sdelete](https://user-images.githubusercontent.com/34108484/66251394-f7f56d00-e74f-11e9-8348-f5d7897c52f4.JPG)


Variable | Type | Value | description
-- | -- | -- | --
LIC_BISF_CLI_SD_runBI | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_SD_runPVSCacheDisk | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_SD_runMCSIO | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_SD_runMCS | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_SD_runOutsideELM | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_SD_runPVSparentDisk | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_POL_SD | DWORD | 1 | If Policy is enabled Registry   Data is set to 1, otherwise it not exist
LIC_BISF_CLI_SD | REG_SZ | YES, NO | IF Policy is enabled Registry   Data is set to YES, if disabled set to NO; otherwise not exist.
LIC_BISF_CLI_SD_SF | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_SD_SF_CUS | REG_SZ | c:\windows\system32 or custom   value | Enter custom searchpath or use   default value c:\windows\system32

**Comment by matthias-schlimm** [comment]
LIC_BISF_SDeleteRun is no longer needed

**Comment by matthias-schlimm** [comment]
05.10.2019 MS: ENH 12 - Configure sDelete for different environments
