### ISSUE TITLE
MCSIO and persistent data

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#126]
MCSIO now introduces the ability to have persistent data on MCS provisioned machines since the shift in architecture to that of PVS. https://docs.citrix.com/en-us/citrix-virtual-apps-desktops/install-configure/machine-catalogs-create.html (Under Machine Creation Services (MCS) storage optimization)

We should make this configurable the same as PVS, but need to be aware of 
a) the version of the VDA (don't want to touch the old MCSIO engine)
b) the difference of behaviour in Azure (double reboots if not using a custom prov scheme) persistent if you are
c) is there any reason not to treat it exactly the same as PVS

**Comment by matthias-schlimm** [comment]
is there something AppLayering special for MCSIO ?

**Comment by matthias-schlimm** [comment]
VDA Version is 1903 minimum, but need the exact Build number that is given out from the BrokerAgent.exe

**Comment by JamesKindon** [comment]
Let me see if can track down a 1903 deployment and get the output
version to you. No idea on app layering - I prefer to pretend it’s not real
:-)

**Comment by matthias-schlimm** [comment]
my 1903 VDA brokeragent.exe is v7.21.0.22

**Comment by matthias-schlimm** [comment]
`IF ($BrokerVersion -ge "7.21"){
				$Global:MCSIO = $true
				Write-BISFLog "BrokerAgent version is $BrokerVersion or greater, support for MCS IO and persistent disk can be used"
			} ELSE {
				$Global:MCSIO = $false
				Write-BISFLog "BrokerAgent version is $BrokerVersion. NO support for MCS IO and persistent disk !!"
			}`

**Comment by matthias-schlimm** [comment]
use Global variable $MCSIO to use redirection

**Comment by matthias-schlimm** [comment]
**GPO:**
![MCSIO](https://user-images.githubusercontent.com/34108484/65372377-c66ca400-dc6f-11e9-92c5-ecbf5553ab08.JPG)


LIC_BISF_POL_MCSCfg | REG_SZ | YES, NO | IF Policy is enabled Registry   Data is set to YES, if disabled set to NO; otherwise not exist.

LIC_BISF_CLI_MCSCfg | DWORD | 1 | If Policy is enabled Registry   Data is set to 1, otherwise it not exist
LIC_BISF_CLI_MCSIODriveLetter | REG_SZ | B-Z | select the Driveletter of the   PVS WriteCacheDrive
LIC_BISF_CLI_MCSIONumberOfPartitions | REG_SZ | 3-5 | Select the Number of Partitions   that you have on the clonded Device
LIC_BISF_CLI_MCSIODisableRedirection | DWORD | 1 | 1 disable the Redirection, 0 or   not exist enable the redirection

**Comment by matthias-schlimm** [comment]
must be tested now
