### ISSUE TITLE
MSI installer creates two entries under the Uninstall key

### ISSUE THREAD

**Issue by jeremyts** [EUCweb/BIS-F#255]
The MSI installer creates two entries under the "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall" key. Not a major issue.just something to be addressed in a future release.

**Comment by matthias-schlimm** [comment]
**Nbr. 1**
![image](https://user-images.githubusercontent.com/34108484/85893063-66082580-b7f2-11ea-88ac-07ee083147ed.png)

**Nbr.2**
![image](https://user-images.githubusercontent.com/34108484/85893083-715b5100-b7f2-11ea-9b34-ed39b12acfb0.png)

**Comment by alphasteff** [comment]
I see also two keys:
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{A6C96C1A-E390-47DC-9594-EE4883516B9A}
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Base Image Script Framework (BIS-F) 7.1912.4.11038

Version: 7.1912.4.11038

**Comment by matthias-schlimm** [comment]
Open up a support ticket at Adv. Installer

**Comment by matthias-schlimm** [comment]
I was able to replicate the described behavior.
It seems this behavior is triggered by the option **override Windows Installer programs list entry** from **Product Details** view:
![image](https://user-images.githubusercontent.com/34108484/86930465-59ab9300-c137-11ea-8ccf-ee8a9104cc7b.png)

This option is activated when selecting a different theme than the **Classic** one.

If you are not using a custom theme, then you can disable this option and see if everything is working as expected. Otherwise, you will have to stick with this option selected and with 2 entries under the **Uninstall** path. One is made by the Windows Installer, under the ProductName property, the other is made by the installer, under the **ProductCode** guid.

**Comment by matthias-schlimm** [comment]
will be fixed in upcoming 7.129.5 release as follows:
 
![image](https://user-images.githubusercontent.com/34108484/89097147-a4d66000-d3dc-11ea-97b8-7bc6968faef1.png)
