### ISSUE TITLE
Azure AD Hybrid Domain Join is now supported for MCS provisioned workloads

### ISSUE THREAD

**Issue by JamesKindon** [EUCweb/BIS-F#285]
Currently BIS-F supports the removal of remove component of Azure AD Hybrid Domain Join

Citrix now supports machines being Azure AD Hybrid Domain Joined, with updated guidance released here
https://support.citrix.com/article/CTX284738

This appears to be MCS only, however we should seek clarity on the PVS support also, as fundamentally it should be the same

I think this should be made an optional configuration to allow for the join phase on machine startup (ADMX option)

**Comment by Deyda** [comment]
The commands are already stored in the 96_PrepBISF_Rearm.ps1 script in the folder \Framework\SubCall\Preparation. But the commands are only executed if you activate Office Rearm in the ADMX and the machine is hosted in Azure. You would have to extend the script with a query if it is an Azure AD Hybrid joined Device and then execute the commands there. I have extended my local version with it and it works. 

For the query I used the following:

https://www.powershellgallery.com/packages/DsReg/1.3.1

**Comment by matthias-schlimm** [comment]
new function Get-BISFDSRegState to getting the value back of an entered Key

Example: $DSRegValue = Get-BISFDSRegState -Key "AzureADjoined"

**Comment by matthias-schlimm** [comment]
A new registry Key/Value must be created under HKLM:\Software\Login Consultants\BIS-F to save the AzureADJoined State from the master. This is required during run the personalization to join the MCS Target.

If azureADJoined is set to YES during preparation the master must leave it as well, as descibed in the CTX KB Article above

**Comment by matthias-schlimm** [comment]
I will create an separated GPO Setting to enable Azure Hybrid AD join, this is Independent from the environment, like native WVD, Citrix MCS, VMware Horizon or other VDI solutions.

**Comment by matthias-schlimm** [comment]
![image](https://user-images.githubusercontent.com/34108484/99907540-8c68b900-2cdd-11eb-8361-3cedffd8a5fa.png)



POL | MS_AAD | Microsoft | AAD | Azure   Active  Directory | HKLM:\SOFTWARE\Policies\Login   Consultants\BISF | LIC_BISF_POL_MS_AAD | REG_SZ | YES, NO | IF Policy is enabled Registry   Data is set to YES, if disabled set to NO; otherwise not exist. | 22.11.20 | Matthias | 7.1912.6
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CLI | MS_AAD_HybridLeaveb | Microsoft | AAD | Enable Azure Active Directory Hybrid Leave | HKLM:\SOFTWARE\Policies\Login   Consultants\BISF | LIC_BISF_CLI_MS_AAD_HybridLeaveb | REG_SZ | YES, NO | If CheckBox is enabled, registry   Data is set to YES, otherwise is set to NO | 22.11.20 | Matthias | 7.1912.6
CLI | MS_AAD_HybridJoinb | Microsoft | AAD | Enable Azure Active Directory   Hybrid Join | HKLM:\SOFTWARE\Policies\Login   Consultants\BISF | LIC_BISF_CLI_MS_AAD_HybridJoinb | REG_SZ | YES, NO | If CheckBox is enabled, registry   Data is set to YES, otherwise is set to NO | 22.11.20 | Matthias | 7.1912.6
  |   |   |   |   |   |   |   |   |   |   |   |

**Comment by matthias-schlimm** [comment]
I will remove the logic from the Office rearm part too

**Comment by matthias-schlimm** [comment]
implemented in developer branch: @JamesKindon  @Deyda  can you grab the Files an run a test

- 97_PrepBISF_PRE_BaseImage.ps1
- 01_PersBISF_MS.ps1
- BaseImageScriptFramework.admx
- BaseImageScriptFramework.adml
- ReleaseNotes.txt

**Note:** 96_PrepBISF_Rearm.ps1 is not changed, if the VM is hosted in Azure and O365 is installed the dsregcmd /leave is running here as well.

**Comment by matthias-schlimm** [comment]
@Deyda I have fixed an issue on weekend in BISF1.psm1 for this one. Any time for testing ?

**Comment by Deyda** [comment]
Ich teste gerade. Danke Matthias.

Mit freundlichen Grüßen
Manuel Winkel

www.deyda.net 
________________________________
Von: Matthias Schlimm <notifications@github.com>
Gesendet: Tuesday, December 1, 2020 3:13:23 PM
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Manuel Winkel <Manuel@deyda.net>; Mention <mention@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Azure AD Hybrid Domain Join is now supported for MCS provisioned workloads (#285)


@Deyda<https://github.com/Deyda> I have fixed an issue on weekend in BISF1.psm1 for this one. Any time for testing ?

**Comment by Deyda** [comment]
Hi Matthias,

habe folgenden Fehler gesehen und er schmeisst mich nicht aus Azure AD raus (GPO ist gesetzt)



Von: Matthias Schlimm <notifications@github.com>
Gesendet: Dienstag, 1. Dezember 2020 15:13
An: EUCweb/BIS-F <BIS-F@noreply.github.com>
Cc: Manuel Winkel <Manuel@deyda.net>; Mention <mention@noreply.github.com>
Betreff: Re: [EUCweb/BIS-F] Azure AD Hybrid Domain Join is now supported for MCS provisioned workloads (#285)


@Deyda<https://github.com/Deyda> I have fixed an issue on weekend in BISF1.psm1 for this one. Any time for testing ?

**Comment by matthias-schlimm** [comment]
schick mal das bis-f logfile bitte

**Comment by matthias-schlimm** [comment]
as Manuel confirmed, it works now
