### ISSUE TITLE
Add sysprep command-line options to ADMX

### ISSUE THREAD

**Issue by JonathanPitre** [EUCweb/BIS-F#94]
Adding the option to customize the sysprep command-line via ADMX so customer can provide a custom answer file or use the /mode:vm switch.

The /mode:vm switch can only be used on VHD and Windows 8 and above. Also that VHD can only be deployed on the same hardware profile.

[Sysprep Command-Line Options](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep-command-line-options)

**Comment by matthias-schlimm** [comment]
![BISF-Sysprep](https://user-images.githubusercontent.com/34108484/66143781-08023500-e608-11e9-9438-70524e7e7f9d.JPG)


LIC_BISF_CLI_SP_CusArgsb | DWORD | 1 | If CheckBox is enabled, registry   Data is set to 1, otherwise not exist
LIC_BISF_CLI_SP_CusArgs | REG_SZ |   | Enter the custom arguments tfor   sysprerp
